---
- name: Install JDK 11 on Ubuntu
  hosts: aws-servers
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Set JAVA_HOME environment variable
      lineinfile:
        dest: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
        state: present
      notify: Reload environment

  handlers:
    - name: Reload environment
      shell: source /etc/environment
      args:
        executable: /bin/bash

