---
- name: Install Apache Tomcat
  hosts: aws-servers
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Tomcat user and group
      group:
        name: tomcat
        state: present

    - name: Create Tomcat installation directory
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Download Tomcat binary
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz"
        dest: /tmp/apache-tomcat-9.0.50.tar.gz

    - name: Extract Tomcat binary
      unarchive:
        src: /tmp/apache-tomcat-9.0.50.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        creates: /opt/tomcat/apache-tomcat-9.0.50

    - name: Set Tomcat environment variables
      lineinfile:
        dest: /etc/profile.d/tomcat.sh
        line: |
          export CATALINA_HOME=/opt/tomcat/apache-tomcat-9.0.50
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        create: yes

    - name: Reload shell environment
      shell: source /etc/profile.d/tomcat.sh
      args:
        executable: /bin/bash
